const chemistryQuotes: string[] = [
  "Chemistry is necessarily an experimental science: its conclusions are drawn from data and its principles supported by evidence. – Michael Faraday",
  "In chemistry, as in life, everything is about balance.",
  "The universe is made of stories, not atoms — but atoms make the stories possible.",
  "Without chemistry, life itself wouldn’t exist. You are 100% chemistry.",
  "The difference between poison and medicine is often just the dose. – Paracelsus",
  "All matter is made of atoms. Chemistry is just the story of how they interact.",
  "Molecules are the brushstrokes of the universe.",
  "Periodic Table: where logic meets mystery.",
  "Even water — the most vital substance — can be deadly. That’s chemistry.",
  "The only letter not appearing on the periodic table is the letter 'J'.",
  "Honey never spoils — archaeologists have found 3,000-year-old honey in Egyptian tombs still edible.",
  "Your body contains enough carbon to fill 9,000 pencils.",
  "Water expands when it freezes — unlike most substances — which is why ice floats.",
  "Astatine is so rare, there’s less than 1 gram in Earth's crust at any time.",
  "Oxygen is colorless as a gas but is pale blue when in liquid form.",
  "Bananas are slightly radioactive due to their potassium-40 content.",
  "You can smell garlic on your breath because of sulfur-containing compounds absorbed into your blood.",
  "Diamond and graphite are both pure carbon, but their atoms are arranged differently.",
  "The human body is about 60% water — and water is a chemical compound!",
  "Chemistry is like cooking: just don't lick the spoon.",
  "The smell of rain comes from a chemical called petrichor.",
  "Teflon, used in non-stick pans, was discovered accidentally.",
  "A single mole of water molecules contains 6.022×10²³ molecules — that's more than stars in the universe!",
  "Helium was discovered in the Sun before it was found on Earth.",
  "The blue color of a flame indicates complete combustion and a hotter flame.",
  "Your stomach produces hydrochloric acid strong enough to dissolve zinc.",
  "Liquid nitrogen boils at −196 °C — it can instantly freeze objects.",
  "Dry ice is solid carbon dioxide — it sublimates directly to gas without melting.",
  "There's enough iron in your blood to make a small nail.",
];

export default chemistryQuotes;
